appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: XyFIEstRUt6Lur+O2d67hYm7eNiB25IYPtoKu6n8fk8GLLR0Y3eGfUIia6WlrZZ9DAXia3Q21uoarMzA89HjemaaQBBx8x4EFekh4ytZstdMQSKVqPy9lHp0i+94bxFgin9bEjBMDU1j7Vph8nrcBPsin1HODC7rgvcqfAv0KnTWV9yI089L/qszfzSd+1NgsiVUUDq4O4Ldk/n+kfC8W+RO/xmAYYvc5mW8j3HXw5QfFclLVfK6mnl6RTLyjD7FgoRFJ1l8Cwn7Qr+gmNu6bXpVxzPHep0vMaG7mouDNHw1NzDY7/EC863WK+yvxEh92RmdimIkdiZItJ6wOsWOG0EoZKi4D4H2ksLu0n749r2ULCWcyUp3YBOaf6sro2uLyJbTOAptYHMyc+CbJGmmqfFfJEk/dJBVMUUPeVcV0OgGO3sBp1x69pqC27dgvyAql4iJozTwoUgh/xQTWPL5/02SNyH7r+fx+21yjpYNFfeT22Rb/wDDA3trO1op2tEn3vXLda2MST1jqT5RQvBO89ureGskXWrVIPICqsq0yRi8vV+S/FbxWpu85vIZ8tQh1UC+NTcizEFEXR9Fz/vM+zu0gx2KbyjMm9mkqnzLFqJs5XrXU1FucplWVl3WQU+/x0mnhkWVJKKeXgubQEYNgS6e3MYbgPf4elZu/69KuGE=}
